/** Code-owned, model-facing tool text. Never derived from appliance data or caller input. */
export const TOOL_SUMMARIES: Readonly<Record<string, string>> = Object.freeze({
  darktrace_get_status: 'Darktrace appliance health: version, probes, traffic and licensing status.',
  darktrace_get_devices: 'List or look up network devices (hosts) known to Darktrace.',
  darktrace_search_devices: 'Free-text device search (hostname, IP, MAC, vendor, tag...) with paging.',
  darktrace_get_device_info: 'Detailed connection/traffic profile for one device.',
  darktrace_get_device_summary: 'Contextual summary for one device.',
  darktrace_get_similar_devices: 'Devices that behave similarly to a given device.',
  darktrace_get_endpoint_details: 'Information Darktrace holds about an external endpoint (IP or hostname).',
  darktrace_list_subnets: 'List monitored subnets.',
  darktrace_get_network_stats: 'Network traffic statistics for the network, a subnet or a device.',
  darktrace_get_connection_details: 'Raw connection/event history for a device or model breach.',
  darktrace_get_metric_data: 'Time series for a metric (e.g. bytes) for a device or connection.',
  darktrace_list_metrics: 'List available metrics, or one metric by mlid.',
  darktrace_list_model_breaches: 'List model breaches (alerts), or fetch one by pbid.',
  darktrace_get_model_breach_comments: 'Read comments on model breaches.',
  darktrace_list_models: 'List detection models, or fetch one by pid.',
  darktrace_list_components: 'List model components (filters/logic), or one by cid.',
  darktrace_get_cves: 'CVE / vulnerability information for devices.',
  darktrace_get_summary_statistics: 'High-level summary statistics (bandwidth, device counts, patterns).',
  darktrace_get_reference_data: 'Reference enumerations and filter types used by other endpoints.',
  darktrace_get_intel_feed: 'Read the watched-domains / intel feed list.',
  darktrace_list_ai_analyst_incidents: 'Cyber AI Analyst incidents: grouped incidents or individual incident events.',
  darktrace_get_ai_analyst_incident_comments: 'Read comments on a Cyber AI Analyst incident.',
  darktrace_list_ai_analyst_investigations: 'List Cyber AI Analyst investigations.',
  darktrace_get_ai_analyst_stats: 'Cyber AI Analyst summary statistics.',
  darktrace_list_antigena_actions: 'Darktrace RESPOND (Antigena) actions: list actions or the pending/active summary.',
  darktrace_list_tags: 'Tags and tagged entities: list tags, one tag, or which devices carry which tags.',
  darktrace_list_pcaps: 'List packet captures and their status.',
  darktrace_download_pcap: 'Download a finished packet capture file (base64, size-bounded, never written to disk).',
  darktrace_advanced_search: 'Advanced Search (log/event search) plus analyze/graph views. query/hash = standard base64 of JSON {"search":"<query>","fields":[],"timeframe":"3600"} (timeframe seconds, max 604800; optional offset, size).',
  darktrace_email_dashboard: 'Darktrace/EMAIL dashboard statistics.',
  darktrace_email_reference_data: 'Darktrace/EMAIL reference data: tags, actions, filters, audit event types.',
  darktrace_email_decode_link: 'Darktrace/EMAIL: decode a rewritten link.',
  darktrace_email_get: 'Darktrace/EMAIL: read one email record by UUID.',
  darktrace_download_email: 'Darktrace/EMAIL: download the raw message of one email (size-bounded).',
  darktrace_email_search: 'Darktrace/EMAIL: search emails with a JSON criteria body.',
  darktrace_email_audit_events: 'Darktrace/EMAIL: read audit events.',
  darktrace_email_action: 'Darktrace/EMAIL: perform an action (e.g. release, hold) on one email.',
  darktrace_acknowledge_ai_analyst_incident: 'Acknowledge or unacknowledge Cyber AI Analyst incident events.',
  darktrace_pin_ai_analyst_incident: 'Pin or unpin Cyber AI Analyst incident events.',
  darktrace_comment_ai_analyst_incident: 'Add a comment to a Cyber AI Analyst incident.',
  darktrace_create_ai_analyst_investigation: 'Start a Cyber AI Analyst investigation on a device.',
  darktrace_acknowledge_model_breach: 'Acknowledge or unacknowledge a model breach.',
  darktrace_comment_model_breach: 'Add a comment to a model breach.',
  darktrace_update_device: 'Update device properties (label, priority, type).',
  darktrace_request_pcap: 'Request a new packet capture for a connection.',
  darktrace_manage_tags: 'Create tags and add/remove tags on devices or entities.',
  darktrace_delete_tag: 'Delete a tag definition.',
  darktrace_antigena_action: 'Activate, extend or clear Darktrace RESPOND (Antigena) actions.',
  darktrace_antigena_manual_action: 'Create a manual RESPOND action (e.g. quarantine or block a device).',
  darktrace_update_intel_feed: 'Add or remove watched domains in the intel feed (removeall wipes the list).',
  darktrace_update_subnet: 'Update subnet settings (label, DHCP, exclusion from monitoring).',
});

export const OPERATION_PURPOSES: Readonly<Record<string, string>> = Object.freeze({
  get_status: 'appliance status',
  get_devices: 'devices (filter by did, ip, mac, sid, seensince)',
  get_devicesearch: 'search devices by query string',
  get_deviceinfo: 'device traffic profile (did required)',
  get_devicesummary: 'device summary (did required)',
  get_similardevices: 'similar devices (did required)',
  get_endpointdetails: 'external endpoint details by ip or hostname',
  get_subnets: 'subnets',
  get_network: 'network statistics',
  get_details: 'connection/event details',
  get_metricdata: 'metric time series',
  get_metrics: 'all metrics',
  get_metrics_mlid: 'one metric',
  get_modelbreaches: 'model breaches (time window, score, device filters)',
  get_modelbreaches_pbid: 'one model breach',
  get_mbcomments: 'comments across breaches',
  get_modelbreaches_pbid_comments: 'comments for one breach',
  get_models: 'models',
  get_models_pid: 'one model',
  get_components: 'components',
  get_components_cid: 'one component',
  get_cves: 'CVEs',
  get_summarystatistics: 'summary statistics',
  get_enums: 'enumerations',
  get_filtertypes: 'filter types',
  get_intelfeed: 'intel feed entries',
  get_aianalyst_groups: 'incidents (groups)',
  get_aianalyst_incidentevents: 'incident events',
  get_aianalyst_incident_comments: 'incident comments',
  get_aianalyst_investigations: 'investigations',
  get_aianalyst_stats: 'AI Analyst stats',
  get_antigena: 'RESPOND actions',
  get_antigena_summary: 'pending/active summary',
  get_tags: 'tags',
  get_tags_tid: 'one tag',
  get_tags_entities: 'tags of a device / devices with a tag',
  get_tags_tid_entities: 'entities of one tag',
  get_pcaps: 'packet captures',
  get_pcaps_filename: 'download one capture',
  get_advancedsearch_api_search_query: 'search (GET, base64 in path)',
  post_advancedsearch_api_search: 'search (POST {hash}; preferred)',
  get_advancedsearch_api_analyze_field_analysis_query: 'field analysis',
  get_advancedsearch_api_graph_graphmode_interval_query: 'time graph',
  get_agemail_api_ep_api_v1_0_dash_action_summary: 'action summary',
  get_agemail_api_ep_api_v1_0_dash_dash_stats: 'dashboard stats',
  get_agemail_api_ep_api_v1_0_dash_data_loss: 'data loss',
  get_agemail_api_ep_api_v1_0_dash_user_anomaly: 'user anomaly',
  get_agemail_api_ep_api_v1_0_resources_tags: 'email tags',
  get_agemail_api_ep_api_v1_0_resources_actions: 'available actions',
  get_agemail_api_ep_api_v1_0_resources_filters: 'search filters',
  get_agemail_api_ep_api_v1_0_system_audit_eventTypes: 'audit event types',
  get_agemail_api_ep_api_v1_0_admin_decode_link: 'decode link',
  get_agemail_api_ep_api_v1_0_emails_uuid: 'email record',
  get_agemail_api_ep_api_v1_0_emails_uuid_download: 'raw email',
  post_agemail_api_ep_api_v1_0_emails_search: 'email search',
  get_agemail_api_ep_api_v1_0_system_audit_events: 'audit events',
  post_agemail_api_ep_api_v1_0_emails_uuid_action: 'email action',
  post_aianalyst_acknowledge: 'acknowledge',
  post_aianalyst_unacknowledge: 'unacknowledge',
  post_aianalyst_pin: 'pin',
  post_aianalyst_unpin: 'unpin',
  post_aianalyst_incident_comments: 'add comment',
  post_aianalyst_investigations: 'create investigation',
  post_modelbreaches_pbid_acknowledge: 'acknowledge',
  post_modelbreaches_pbid_unacknowledge: 'unacknowledge',
  post_modelbreaches_pbid_comments: 'add comment',
  post_devices: 'update device',
  post_pcaps: 'request capture',
  post_tags: 'create tag',
  post_tags_entities: 'tag a device (form)',
  post_tags_tid_entities: 'add entities to a tag',
  delete_tags_entities: 'remove a tag from a device (did + tag)',
  delete_tags_tid_entities_teid: 'remove one tag-entity link',
  delete_tags_tid: 'delete tag',
  post_antigena: 'activate/extend/clear actions',
  post_antigena_manual: 'manual action',
  post_intelfeed: 'update intel feed',
  post_subnets: 'update subnet',
});
